name: Deploy Django Application to EC2

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          # Navigate to your project directory
          cd /home/ubuntu/your-project-directory

          # Pull the latest changes
          git pull origin main  # Change this to your deployment branch

          # Activate the virtual environment
          source venv/bin/activate

          # Install dependencies
          pip install -r requirements.txt

          # Apply migrations
          python manage.py migrate

          # Collect static files
          python manage.py collectstatic --noinput

          # Restart Gunicorn
          sudo systemctl restart gunicorn

          # Restart Nginx (if necessary)
          sudo systemctl restart nginx
        EOF
